---
- name: Clone yay GIT repository to /tmp/yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: /tmp/yay
    force: true

- name: Build yay
  environment:
    HOME: /tmp/yay
  shell: |
    cd /tmp/yay
    makepkg -fcr
  args:
    executable: /bin/bash

- name: Install yay
  become: true
  shell: pacman --noconfirm -U /tmp/yay/yay*.pkg.tar.xz
  args:
    executable: /bin/bash

- name: Remove /tmp/yay
  file:
    path: /tmp/yay
    state: absent
