---
- hosts: localhost
  roles:
    - upgrade
    - sublime-text
    - git
    - i3
    - firefox-developer-edition
    - sound
    - bluetooth
    - rclone
    - steam
    - gebaar
    - sbupdate
    - install
  vars:
    sbupdate_disk: /dev/nvme0n1
    sbupdate_partition_number: 1
    git_user: Firstname Lastname
    git_mail: adress@domain.com
    i3_dpi: 192
    i3_background_color: '#000000'
    i3_background_image: /usr/share/pixmaps/hextille-background.svg
    install_pacman_packages:
      - gvfs-mtp
      - htop
      - noto-fonts-cjk
      - xss-lock
      - i3lock
      - keepassxc
      - bolt
    install_pikaur_packages:
    install_autostart:
      - comment: Start xss-lock
        executable: xss-lock -- i3lock --color=000000 --ignore-empty-password --show-failed-attempts
      - comment: Start KeePassXC password manager
        executable: keepassxc
