---
- hosts: localhost
  roles:
    - upgrade
    - sublime-text
    - git
    - i3
    - gebaar
    - firefox-developer-edition
    - chromium
    - sound
    - bluetooth
    - sbupdate
    - install
  vars:
    partition_block_device: /dev/sda
    partition_efi_number: p1
    git_user: Firstname Lastname
    git_mail: adress@domain.com
    dpi: 192
    install_pacman_packages:
      - htop
      - xss-lock
      - i3lock
      - keepassxc
      - bolt
    install_pikaur_packages:
      - odrive-bin
