---
- hosts: localhost
  roles:
    - upgrade
    - sublime-text
    - git
    - i3
    - gebaar
    - firefox-developer-edition
    - chromium
    - sound
    - bluetooth
    - sbupdate
    - steam
    - install
  vars:
    partition_block_device: /dev/sda
    partition_efi_number: p1
    git_user: Firstname Lastname
    git_mail: adress@domain.com
    dpi: 192
    background_color: '#000000'
    background_image: /usr/share/pixmaps/hextille-background.svg
    install_pacman_packages:
      - gvfs-mtp
      - htop
      - xss-lock
      - i3lock
      - keepassxc
      - bolt
      - noto-fonts-cjk
    install_pikaur_packages:
      - odrive-bin
    install_autostart:
      - comment: Start xss-lock
        executable: xss-lock -- i3lock --color=000000 --ignore-empty-password --show-failed-attempts
      - comment: Start ODrive - GUI client for Google Drive on linux https://github.com/liberodark/ODrive
        executable: nm-online && /opt/OpenDrive/odrive
      - comment: Start KeePassXC password manager
        executable: keepassxc
