---
- hosts: localhost
  roles:
    - partition
    - create-efi-keys
    - network
    - adduser
  vars:
    partition_block_device: /dev/sda
    partition_efi_number: 1
    partition_efi_size: 256M
    partition_root_number: 2
    partition_root_password: test
    efi_keys_location: /mnt/root/secure-boot
    bootloader_video_driver: i915
    chroot_hostname: testhost
    chroot_extra_packages: intel-ucode xf86-video-intel terminus-font
    user_name: test
    user_password: test
    user_fullname: Firstname Lastname
    bash_executable: /usr/bin/arch-chroot /mnt /bin/bash
