---
- name: Add sublime-text repository to /etc/pacman.conf
  become: true
  blockinfile:
    path: '/etc/pacman.conf'
    block: |
      [sublime-text]
      Server = https://download.sublimetext.com/arch/stable/x86_64

- name: Check if sublime public key is installed
  command: pacman-key --finger 8A8F901A
  register: sublime_key_installed
  failed_when: false

- name: Install pacman keys for sublime-text
  become: true
  shell: >
    curl https://download.sublimetext.com/sublimehq-pub.gpg |
    pacman-key --add - &&
    pacman-key --lsign-key 8A8F901A &&
    pacman --sync --refresh
  args:
    warn: false
    executable: /bin/bash
  when: sublime_key_installed.rc != 0

- name: Install sublime-text package
  become: true
  command: >
    pacman --noconfirm --sync
    sublime-text
  args:
    warn: false

- name: Create templated configuration direcories sublime-text
  file:
    path: '~/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: templates/user_home
  when: item.state == 'directory'

- name: Create templated configurations of sublime-text
  template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_filetree: templates/user_home
  when: item.state == 'file'

- name: Add SUDO_EDITOR to /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^SUDO_EDITOR='
    line: 'SUDO_EDITOR=subl -w'
