---
- name: Install sublime-text package
  command: >
    pikaur --noconfirm --sync
    sublime-text-3

- name: Create templated configuration direcories sublime-text
  file:
    path: '~/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: templates/user_home
  when: item.state == 'directory'

- name: Create templated configurations of sublime-text
  template:
    src: '{{ item.src }}'
    dest: '~/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_filetree: templates/user_home
  when: item.state == 'file'

- name: Add SUDO_EDITOR to /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^SUDO_EDITOR='
    line: 'SUDO_EDITOR=subl -w'
