---
- name: Install network packages
  become: true
  pacman:
    state: latest
    name:
      - virtualbox-guest-utils
      - virtualbox-guest-dkms

- name: Enable VirtualBox service
  become: true
  systemd:
    name: vboxservice
    enabled: true
