---
- name: Install network packages
  become: true
  pacman:
    update_cache: true
    state: latest
    name:
      - virtualbox-guest-utils
      - virtualbox-guest-dkms

- name: Start network service
  become: true
  systemd:
    name: vboxservice
    state: started
    enabled: true
