---
- name: Install necessary packages
  become: true
  command: >
    pacman --noconfirm --sync
    xorg
    xorg-apps
    xorg-fonts
    xf86-input-keyboard
    xf86-input-mouse
    xf86-input-libinput
  args:
    warn: false
