---
- name: Install AMD drivers
  become: true
  command: >
    pacman --noconfirm --sync
    xf86-video-amdgpu
    mesa
    vulkan-radeon

- name: Install AMD optional packages
  become: true
  command: >
    pacman --noconfirm --sync --asdeps
    rocm-smi-lib

- name: Install AMD multilib drivers
  become: true
  command: >
    pacman --noconfirm --sync
    lib32-mesa
    lib32-vulkan-radeon
  when: video_multilib | bool

- name: Create AMD templated configuration direcories
  become: true
  file:
    path: '/{{ item.path }}'
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: templates_amdgpu/
  when: item.state == 'directory' and not item.path.startswith('user_home')

- name: Create AMD templated configurations
  become: true
  template:
    src: '{{ item.src }}'
    dest: '/{{ item.path }}'
    mode: '{{ item.mode }}'
  with_filetree: templates_amdgpu/
  when: item.state == 'file' and not item.path.startswith('user_home')
