---
- name: Install Intel 3D and VAPI drivers
  become: true
  command: >
    pacman --noconfirm --sync
    mesa
    vulkan-intel
    intel-media-driver
    intel-compute-runtime

- name: Add LIBVA_DRIVER_NAME to /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^LIBVA_DRIVER_NAME='
    line: 'LIBVA_DRIVER_NAME=iHD'

- name: Install multilib Intel 3D and VAPI drivers
  become: true
  command: >
    pacman --noconfirm --sync
    lib32-mesa
    lib32-vulkan-intel
  when: video_multilib | bool
