---
- name: Install Nvidia 3D, vdpau and VAPI drivers
  become: true
  command: >
    pacman --noconfirm --sync
    nvidia-dkms
    nvidia-settings
    libvdpau
    libva-vdpau-driver
    opencl-nvidia
    cuda
  args:
    warn: false

- name: Add LIBVA_DRIVER_NAME to /etc/environment
  become: true
  lineinfile:
    path: /etc/environment
    regexp: '^LIBVA_DRIVER_NAME='
    line: 'LIBVA_DRIVER_NAME=vdpau'

- name: Install multilib Nvidia 3D, vdpau and VAPI drivers
  become: true
  command: >
    pacman --noconfirm --sync
    lib32-nvidia-utils
    lib32-libvdpau
    lib32-libva-vdpau-driver
    lib32-opencl-nvidia
  args:
    warn: false
  when: video_multilib | bool
