---
- name: Install bluetooth suport
  become: true
  command: >
    pacman --noconfirm --sync
    blueman
    pulseaudio-bluetooth
  args:
    warn: false

- name: Enable bluetooth service
  become: true
  command: systemctl enable bluetooth.service
  args:
    warn: false

- name: Augument global_autostart variable for autostart entry creation
  set_fact:
    global_autostart: '{{ global_autostart | default([]) + bluetooth_autostart }}'
