---
- name: Install efibootmgr
  become: true
  command: >
    pacman --noconfirm --sync
    efibootmgr

- name: Install sbupdate
  command: >
    paru --noconfirm --sync
    sbupdate-git

- name: Configure /etc/sbupdate.conf
  become: true
  lineinfile:
    path: /etc/sbupdate.conf
    regexp: '^#?{{ item.key | regex_escape() }}='
    line: '{{ item.key }}="{{ item.value }}"'
  with_dict:
    KEY_DIR: /root/secure-boot
    ESP_DIR: /boot/efi
    OUT_DIR:
    SPLASH:
    BACKUP: 0
    CMDLINE_DEFAULT: root=/dev/mapper/root quiet splash

- name: Configure /etc/mkinitcpio.d/linux-zen.preset
  become: true
  lineinfile:
    path: /etc/mkinitcpio.d/linux-zen.preset
    regexp: '^\s*({{ item | regex_escape() }}=.*)'
    line: '#\g<1>'
    backrefs: yes
  loop:
    - default_uki
    - default_options

- name: Remove previous EFI boot loader
  become: true
  command: >
    rm -rf
    /etc/efi-image-kernel-parameters
    /boot/efi/EFI

- name: Run sbupdate
  become: true
  command: sbupdate

- name: Check whether EFI entry is allready created
  shell: efibootmgr | grep "Arch Linux"
  args:
    executable: /bin/bash
  register: efi_entry_created
  failed_when: false

- name: Create EFI entry
  become: true
  command: >
    efibootmgr
    --create
    --label "Arch Linux"
    --disk {{ sbupdate_disk }}
    --part {{ sbupdate_partition_number | string | regex_search('[0-9]+') }}
    --loader linux-zen-signed.efi
    --verbose
  when: efi_entry_created.rc != 0
