---
i3_autostart:
  - comment: Start picom compositor
    executable: picom

  - comment: Start Network Manager applet
    executable: nm-applet

  - comment: Start Thunar in daemon mode
    executable: thunar --daemon

  - comment: Start PolicyKit authentication agent
    executable: /usr/lib/mate-polkit/polkit-mate-authentication-agent-1
