---
- name: Install openssh
  become: true
  command: >
    pacman --noconfirm --sync
    openssh

- name: Copy configuration
  become: true
  copy:
    src: files/
    dest: /

- name: Enable sshd.service
  become: true
  command: systemctl enable sshd.service
