---
- name: Install openssh
  become: true
  command: >
    pacman --noconfirm --sync
    openssh
  args:
    warn: false

- name: Enable sshd.service
  become: true
  command: systemctl enable sshd.service
  args:
    warn: false
