---
- name: Install maven
  become: true
  command: >
    pacman --noconfirm --sync
    maven

- name: Create /etc/bash_completion.d if does not exist
  become: true
  file:
    path: /etc/bash_completion.d
    state: directory
    mode: 0755

- name: Download and install maven bash completions from {{ maven_bash_completion_download_url }}
  become: true
  get_url:
    url: '{{ maven_bash_completion_download_url }}'
    dest: /etc/bash_completion.d/mvn
    mode: 0644

