---
- name: Install docker-ce and docker-compose
  become: true
  command: >
    pacman --noconfirm --sync
    docker-compose
  args:
    warn: false

- name: Copy default configuration
  become: true
  copy:
    src: etc/
    dest: /etc

- name: Adding "{{ ansible_user_id }}" user to usergroup "docker". This will allow "{{ ansible_user_id }}" user execute Docker commands without sudo
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true
