---
partition_block_device: /dev/sda
partition_efi_number: 1
partition_efi_size: 256M
partition_root_number: 2
partition_root_password:
bootloader_video_driver: i915
chroot_extra_packages: 
chroot_hostname: testhost
