---
partition_disk_list:
  - device: /dev/sda
    partition:
      - number: 1
        size: 256M
        typecode: EF00
        name: UEFI
      - number: 2
        size: 0
        typecode: 8304
        name: ROOT
