---
- name: Create EFI
  become: true
  command: >
    sgdisk
    --zap-all
    --new={{ partition_efi_number }}:0:+{{ partition_efi_size }}
    --typecode={{ partition_efi_number }}:EF00
    --change-name={{ partition_efi_number }}:UEFI
    --new={{ partition_root_number }}:0:0
    --typecode={{ partition_root_number }}:8304
    --change-name={{ partition_root_number }}:ROOT
    --print
    {{ partition_block_device }}

- name: Format EFI
  become: true
  command: mkfs.fat -n UEFI -F 32 {{ partition_efi_device }}

- name: Encrypt device
  become: true
  shell: >
    cryptsetup luksFormat {{ partition_root_device }} --type luks2 --force-password
    --cipher=aes-xts-plain64 --key-size=512 --use-random
  args:
    stdin: '{{ partition_root_password }}'
    executable: /bin/bash
  when: partition_root_password is not none

- name: Open encrypted device
  become: true
  shell: cryptsetup open {{ partition_root_device }} root --type luks --allow-discards
  args:
    stdin: '{{ partition_root_password }}'
    executable: /bin/bash
  when: partition_root_password is not none

- name: Format ROOT partition
  become: true
  command: mkfs.ext4 -m 0 -L ROOT {{ partition_root_alias }}
