---
- name: Mount ROOT partition
  become: true
  command: mount {{ partition_root_alias }} /mnt
  args:
    warn: false

- name: Create boot EFI directory
  become: true
  file:
    path: /mnt/boot/efi
    state: directory

- name: Mount EFI
  become: true
  command: mount {{ partition_efi_device }} /mnt/boot/efi
  args:
    warn: false

- name: Install Swedish mirrorlist
  become: true
  copy:
    src: templates/etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist

- name: Install base packages to chroot
  become: true
  command: >
    pacstrap /mnt
    bash
    bash-completion
    binutils
    bzip2
    coreutils
    cryptsetup
    device-mapper
    diffutils
    e2fsprogs
    file
    filesystem
    findutils
    gawk
    gcc-libs
    gettext
    glibc
    grep
    gzip
    inetutils
    iproute2
    iputils
    less
    licenses
    linux-lts
    linux-firmware
    logrotate
    man-db
    man-pages
    nano
    pacman
    pciutils
    procps-ng
    psmisc
    sed
    shadow
    sudo
    sysfsutils
    systemd-sysvcompat
    tar
    texinfo
    usbutils
    util-linux
    vi
    which
    {{ chroot_extra_packages }}

- name: Execute systemd-firstboot on chroot (Setup default configurations)
  become: true
  command: >
    systemd-firstboot
    --root=/mnt
    --locale=en_US.UTF-8
    --locale-messages=en_US.UTF-8
    --keymap=us
    --timezone=Europe/Stockholm
    --hostname={{ chroot_hostname }}
    --setup-machine-id

- name: Check if /mnt/usr/share/kbd/consolefonts/ter-132b.psf.gz exists
  stat:
    path: /mnt/usr/share/kbd/consolefonts/ter-132b.psf.gz
  register: highdpi_console_font

- name: Add high DPI console font to /etc/vconsole.conf
  become: true
  lineinfile:
    path: /mnt/etc/vconsole.conf
    regexp: '^{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  with_dict:
    FONT: ter-132b
    FONT_MAP: 8859-1
  when: highdpi_console_font.stat.exists

- name: Execute systemd-sysusers on chroot (Install default Arch Linux users and groups)
  become: true
  command: systemd-sysusers --root=/mnt
