---
- name: Mount ROOT partition
  become: true
  command: mount {{ root_partition }} /mnt
  args:
    warn: false

- name: Create boot EFI directory
  become: true
  file:
    path: /mnt/boot/efi
    state: directory

- name: Mount EFI
  become: true
  command: mount {{ efi_partition }} /mnt/boot/efi
  args:
    warn: false

- name: Install Swedish mirrorlist
  become: true
  copy:
    src: templates/etc/pacman.d/mirrorlist
    dest: /etc/pacman.d/mirrorlist

- name: Install base packages to chroot
  become: true
  command: >
    pacstrap /mnt
    bash
    bash-completion
    binutils
    bzip2
    coreutils
    device-mapper
    diffutils
    e2fsprogs
    file
    filesystem
    findutils
    gawk
    gcc-libs
    gettext
    glibc
    grep
    gzip
    inetutils
    iproute2
    iputils
    less
    licenses
    linux-lts
    linux-firmware
    logrotate
    man-db
    man-pages
    nano
    pacman
    pciutils
    procps-ng
    psmisc
    sed
    shadow
    sudo
    sysfsutils
    systemd-sysvcompat
    tar
    texinfo
    usbutils
    util-linux
    vi
    which

- name: Execute systemd-firstboot on chroot (Setup default configurations)
  become: true
  command: >
    systemd-firstboot
    --root=/mnt
    --locale=en_US.UTF-8
    --locale-messages=en_US.UTF-8
    --keymap=us
    --timezone=Europe/Stockholm
    --hostname={{ hostname }}
    --setup-machine-id

- name: Execute systemd-sysusers on chroot (Install default Arch Linux users and groups)
  become: true
  command: systemd-sysusers --root=/mnt
