---
- name: Upgrade pacman packages
  become: true
  command: pacman --sync --refresh --sysupgrade --noconfirm
  args:
    warn: false

- name: Install pikaur dependencies
  become: true
  command: >
    pacman --noconfirm --sync
    base-devel
  args:
    warn: false

- name: Clone pikaur GIT repository to /tmp/pikaur
  git:
    repo: https://aur.archlinux.org/pikaur.git
    dest: /tmp/pikaur
    force: true

- name: Build pikaur
  environment:
    HOME: /tmp/pikaur
  shell: |
    cd /tmp/pikaur
    makepkg --noconfirm --install --cleanbuild --syncdeps --rmdeps --clean --force
  args:
    executable: /bin/bash

- name: Install optional dependencies
  become: true
  command: >
    pacman --noconfirm --sync --asdeps
    asp
  args:
    warn: false

- name: Remove /tmp/pikaur
  file:
    path: /tmp/pikaur
    state: absent
