---
- name: Install pikaur dependencies
  become: true
  pacman:
    state: latest
    name:
      - base-devel
      - pyalpm
      - asp

- name: Clone pikaur GIT repository to /tmp/pikaur
  become: true
  become_user: nobody
  git:
    repo: https://aur.archlinux.org/pikaur.git
    dest: /tmp/pikaur
    force: true

- name: Build pikaur
  become: true
  become_user: nobody
  shell: |
    cd /tmp/pikaur
    makepkg -cr
  args:
    executable: /bin/bash

- name: Install pikaur
  become: true
  shell: pacman --noconfirm -U /tmp/pikaur/pikaur*.pkg.tar.xz
  args:
    executable: /bin/bash

- name: Remove /tmp/pikaur
  become: true
  file:
    path: /tmp/pikaur
    state: absent

- name: Reinstall with pikaur
  become: true
  command: pikaur --noconfirm -Syu pikaur
