---
- name: Check whether pikaur is installed and on system path 
  shell: command -v pikaur
  args:
    executable: /bin/bash
  register: pikaur_installed
  failed_when: false

- include_tasks: install.yaml
  when: pikaur_installed.rc != 0
