---
- name: Set up hostname
  become: true
  template:
    src: etc/hostname
    dest: /etc/hostname

- name: Install network packages
  become: true
  pacman:
    state: latest
    name: networkmanager

- name: Enable network service
  become: true
  command: systemctl enable NetworkManager
