---
- name: Check if mdadm is installed
  become: true
  command: pacman --query --info mdadm
  ignore_errors: true
  register: bootloader_mdadm

- name: Check if cryptsetup is installed
  become: true
  command: pacman --query --info cryptsetup
  ignore_errors: true
  register: bootloader_cryptsetup

- name: Configure /etc/mkinitcpio.conf
  become: true
  lineinfile:
    path: /etc/mkinitcpio.conf
    regexp: '^{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  loop: '{{ query("dict", lines) }}'
  vars:
    lines:
      HOOKS: (base systemd plymouth autodetect keyboard sd-vconsole modconf block {{ 'mdadm_udev ' if bootloader_mdadm.rc == 0 }}{{ 'sd-encrypt ' if bootloader_cryptsetup.rc == 0 }}filesystems fsck)

- name: Configure /etc/plymouth/plymouthd.conf
  become: true
  lineinfile:
    path: /etc/plymouth/plymouthd.conf
    regexp: '^{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  loop: '{{ query("dict", lines) }}'
  vars:
    lines:
      ShowDelay: 0
      DialogClearsFirmwareBackground: false

- name: Set plymouth theme and regenerate initrd image
  become: true
  command: plymouth-set-default-theme --rebuild-initrd bgrt

- name: Check if sbupdate is installed
  stat:
    path: /bin/sbupdate
  register: sbupdate

- name: Run sbupdate
  become: true
  command: sbupdate
  when: sbupdate.stat.exists

- name: Enable lightdm service
  become: true
  systemd:
    name: lightdm
    enabled: true

- name: Configure /etc/lightdm/users.conf
  become: true
  lineinfile:
    path: /etc/lightdm/users.conf
    regexp: '^#?{{ "hidden-shells" | regex_escape() }}='
    line: 'hidden-shells=/bin/false /usr/bin/nologin /sbin/nologin'

- name: Copy a /usr/share/xgreeters/lightdm-slick-greeter.desktop to .../lightdm-slick-greeter-no-scale.desktop
  become: true
  copy:
    src: /usr/share/xgreeters/lightdm-slick-greeter.desktop
    dest: /usr/share/xgreeters/lightdm-slick-greeter-no-scale.desktop
    remote_src: true
    force: true

- name: Disable GDK_SCALE on /usr/share/xgreeters/lightdm-slick-greeter-no-scale.desktop
  become: true
  lineinfile:
    path: /usr/share/xgreeters/lightdm-slick-greeter-no-scale.desktop
    regexp: '^Exec='
    line: 'Exec=env --unset=GDK_SCALE --unset=GDK_DPI_SCALE slick-greeter'

- name: Configure /etc/lightdm/lightdm.conf
  become: true
  lineinfile:
    path: /etc/lightdm/lightdm.conf
    regexp: '^#?{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  loop: '{{ query("dict", lines) }}'
  vars:
    lines:
      greeter-session: lightdm-slick-greeter-no-scale
