---
- name: Install opera
  become: true
  command: >
    pacman --noconfirm --sync
    opera
    opera-ffmpeg-codecs
  args:
    warn: false

- name: Create opera config directory
  file:
    path: '~/.config/opera'
    state: directory

- name: Create default opera preferences
  copy:
    content: '{{ opera_preferences | to_json }}'
    dest: '~/.config/opera/Preferences'
    force: false
