---
- name: Upgrade pacman packages
  become: true
  command: pacman --sync --refresh --sysupgrade --noconfirm

- name: Upgrade AUR packages
  command: pikaur --sync --refresh --sysupgrade --noconfirm
