---
- name: Install binutils
  become: true
  pacman:
    state: latest
    name: binutils

- name: Find encrypted disk id
  become: true
  command: find -L /dev/disk/by-id -samefile {{ encrypted_device }} -print -quit
  register: encrypted_disk_id

- name: Find EFI disk id
  become: true
  command: blkid -o value -s UUID {{ efi_partition }}
  register: efi_disk_id

- name: Create templated configurations
  become: true
  template:
    src: '{{ item.src }}'
    dest: '/mnt/{{ item.path }}'
  with_filetree: templates/
  when: item.state == 'file'

- name: Configure /etc/mkinitcpio.conf
  become: true
  lineinfile:
    path: /mnt/etc/mkinitcpio.conf
    regexp: '^{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  with_dict:
    FILES: (/boot/efi/{{ luks_header_file }})
    HOOKS: (base systemd autodetect keyboard sd-vconsole modconf block sd-encrypt filesystems fsck)

- name: Regenerate initrd image
  become: true
  command: arch-chroot /mnt mkinitcpio --preset linux

- name: Generate linux-signed.efi
  become: true
  shell: >
    echo -n "root=/dev/mapper/{{ encrypted_device_name }}" > /tmp/cmdline.tmp ;
    objcopy
    --add-section .osrel="/etc/os-release"                --change-section-vma .osrel=0x20000
    --add-section .cmdline="/tmp/cmdline.tmp"             --change-section-vma .cmdline=0x30000
    --add-section .splash="/sys/firmware/acpi/bgrt/image" --change-section-vma .splash=0x40000
    --add-section .linux="/mnt/boot/vmlinuz-linux"        --change-section-vma .linux=0x2000000
    --add-section .initrd="/mnt/boot/initramfs-linux.img" --change-section-vma .initrd=0x3000000
    "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "/mnt/boot/efi/linux-signed.efi"
  args:
    creates: /mnt/boot/efi/linux-signed.efi
    executable: /bin/bash

- name: Create EFI entry
  become: true
  shell: >
    efibootmgr
    --disk {{ efi_device }}
    --part {{ efi_partition_number }}
    --create
    --label "Arch Linux"
    --loader linux-signed.efi
    --verbose
  args:
    executable: /bin/bash
