---
- name: Fetch librewolf PGP keys
  ansible.builtin.command: gpg --fetch-keys https://gpg.librewolf.net

- name: Install librewolf
  ansible.builtin.command: >
    paru --noconfirm --sync
    librewolf-bin

- name: Configure initial librewolf settings
  ansible.builtin.copy:
    src: user_home/
    dest: '~'
