---
- name: Find UUID's
  become: true
  command: blkid -o value -s UUID {{ item.device }}
  loop: '{{ bootloader_mount_list + encryption_list }}'
  register: bootloader_uuid_list

- name: Create templated configuration direcories
  become: true
  file:
    path: /mnt/{{ item.path }}
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: templates/
  when: item.state == 'directory'

- name: Create templated configurations
  become: true
  template:
    src: '{{ item.path }}'
    dest: '/mnt/{{ item.path }}'
    mode:  preserve
  with_filetree: templates/
  when: item.state == 'file'

- name: Configure /etc/mkinitcpio.conf
  become: true
  lineinfile:
    path: /mnt/etc/mkinitcpio.conf
    regexp: '^{{ item.key | regex_escape() }}='
    line: '{{ item.key }}={{ item.value }}'
  loop: '{{ query("dict", lines) }}'
  vars:
    lines:
      MODULES: ({{ bootloader_video_driver }})
      HOOKS: (base systemd keyboard sd-vconsole autodetect microcode modconf block {{ 'mdadm_udev ' if raid_list }}{{ 'sd-encrypt ' if encryption_list }}filesystems fsck)

- name: Find all mkinitcpio preset files
  become: true
  find:
    paths: /mnt/etc/mkinitcpio.d
    patterns: '*.preset'
  register: partition_presets

- name: Remove all fallback preset configurations
  become: true
  lineinfile:
    path: '{{ item.path }}'
    regexp: '^#?fallback_'
    state: absent
  loop: '{{ partition_presets.files }}'

- name: Remove all fallback presets
  become: true
  lineinfile:
    path: '{{ item.path }}'
    regexp: '^PRESETS='
    line: PRESETS=('default')
  loop: '{{ partition_presets.files }}'

- name: Configure /etc/mkinitcpio.d/linux-zen.preset
  become: true
  lineinfile:
    path: /mnt/etc/mkinitcpio.d/linux-zen.preset
    regexp: '^#?{{ item.key | regex_escape() }}='
    line: '{{ item.key }}="{{ item.value }}"'
  loop: '{{ query("dict", lines) }}'
  vars:
    lines:
      default_uki: /boot/efi/EFI/BOOT/BOOTX64.EFI
      default_options: --cmdline /etc/efi-image-kernel-parameters

- name: Create /boot/efi/EFI/BOOT directory
  ansible.builtin.file:
    path: /mnt/boot/efi/EFI/BOOT
    state: directory

- name: Delete old initrd images
  become: true
  command: find /mnt/boot -type f -name '*.img' -exec rm -f {} \;

- name: Regenerate initrd image
  become: true
  command: arch-chroot /mnt mkinitcpio --allpresets
