---
- name: Install docker and docker-compose
  become: true
  command: >
    pacman --noconfirm --sync
    docker
    docker-compose

- name: Copy default configuration
  become: true
  copy:
    src: etc/
    dest: /etc

- name: Ensure group "docker" exists
  become: true
  group:
    name: docker
    state: present

- name: Adding "{{ ansible_user_id }}" user to usergroup "docker". This will allow "{{ ansible_user_id }}" user execute Docker commands without sudo
  become: true
  user:
    name: '{{ ansible_user_id }}'
    groups: docker
    append: true

- name: Enable docker.service
  become: true
  command: systemctl enable docker.service
