---
- name: Install pulse audio
  become: true
  command: >
    pacman --noconfirm --sync
    pasystray
    paprefs
    pavucontrol
    pulseaudio

- name: Augument global_autostart variable for autostart entry creation
  set_fact:
    global_autostart: '{{ global_autostart | default([]) + sound_autostart }}'
