---
- name: Install {{ install_pacman_packages | default('nothing', true) }}
  become: true
  command: >
    pacman --noconfirm --sync
    {{ install_pacman_packages | join(' ') }}
  when: install_pacman_packages is iterable

- name: Install {{ install_pikaur_packages | default('nothing', true) }}
  command: >
    pikaur --noconfirm --sync
    {{ install_pikaur_packages | join(' ') }}
  when: install_pikaur_packages is iterable

- name: Augument global_autostart variable for autostart entry creation
  set_fact:
    global_autostart: '{{ global_autostart | default([]) + install_autostart }}'
